insert into person (first_name, last_name, profession) values ('Gabriellia', 'Syplus', 'Database Administrator II');
insert into person (first_name, last_name, profession) values ('Sergio', 'Cannaway', 'Product Engineer');
insert into person (first_name, last_name, profession) values ('Simeon', 'Lehon', 'Food Chemist');
insert into person (first_name, last_name, profession) values ('Deny', 'Domerc', 'Chemical Engineer');
insert into person (first_name, last_name, profession) values ('Garner', 'Glanert', 'Computer Systems Analyst IV');
insert into person (first_name, last_name, profession) values ('Maureen', 'Kenforth', 'VP Marketing');
insert into person (first_name, last_name, profession) values ('Yettie', 'Waylen', 'Accounting Assistant I');
insert into person (first_name, last_name, profession) values ('Jemmy', 'Box', 'Database Administrator II');
insert into person (first_name, last_name, profession) values ('Helen', 'Penley', 'Budget/Accounting Analyst II');
insert into person (first_name, last_name, profession) values ('Wren', 'Geraudy', 'Geological Engineer');
insert into person (first_name, last_name, profession) values ('Dulsea', 'Durtnell', 'VP Marketing');
insert into person (first_name, last_name, profession) values ('Raynell', 'Tilt', 'Junior Executive');
insert into person (first_name, last_name, profession) values ('Pryce', 'Huckstepp', 'Business Systems Development Analyst');
insert into person (first_name, last_name, profession) values ('Tiffy', 'Helstrom', 'Environmental Tech');
insert into person (first_name, last_name, profession) values ('Piggy', 'Malcolmson', 'Assistant Media Planner');
insert into person (first_name, last_name, profession) values ('Ric', 'Howell', 'Developer II');
insert into person (first_name, last_name, profession) values ('Mayer', 'Jakucewicz', 'Analog Circuit Design manager');
insert into person (first_name, last_name, profession) values ('Melony', 'Klaus', 'Staff Scientist');
insert into person (first_name, last_name, profession) values ('Ivie', 'Clawe', 'Quality Control Specialist');
insert into person (first_name, last_name, profession) values ('Gleda', 'Drummond', 'Software Test Engineer III');
insert into person (first_name, last_name, profession) values ('Evyn', 'Kenwrick', 'Data Coordiator');
insert into person (first_name, last_name, profession) values ('Duky', 'Brumbye', 'Senior Developer');
insert into person (first_name, last_name, profession) values ('Merrielle', 'Parrish', 'Data Coordiator');
insert into person (first_name, last_name, profession) values ('Bob', 'Chater', 'Programmer Analyst II');
insert into person (first_name, last_name, profession) values ('Rhys', 'Lavens', 'Human Resources Assistant II');
insert into person (first_name, last_name, profession) values ('Teressa', 'Fetherby', 'General Manager');
insert into person (first_name, last_name, profession) values ('Jeth', 'Haselhurst', 'Recruiter');
insert into person (first_name, last_name, profession) values ('Dave', 'Gouldie', 'Software Consultant');
insert into person (first_name, last_name, profession) values ('Arleyne', 'Gligorijevic', 'Technical Writer');
insert into person (first_name, last_name, profession) values ('Izak', 'Radeliffe', 'Marketing Assistant');
insert into person (first_name, last_name, profession) values ('Nanette', 'Janek', 'Clinical Specialist');
insert into person (first_name, last_name, profession) values ('Enid', 'Lafflina', 'Human Resources Manager');
insert into person (first_name, last_name, profession) values ('Judi', 'Cruikshanks', 'Engineer III');
insert into person (first_name, last_name, profession) values ('Mae', 'Hartshorn', 'GIS Technical Architect');
insert into person (first_name, last_name, profession) values ('Hubie', 'Feely', 'Statistician IV');
insert into person (first_name, last_name, profession) values ('Gusella', 'De Bellis', 'Business Systems Development Analyst');
insert into person (first_name, last_name, profession) values ('Garv', 'Kilkenny', 'Senior Financial Analyst');
insert into person (first_name, last_name, profession) values ('Darice', 'Aughtie', 'Software Engineer II');
insert into person (first_name, last_name, profession) values ('Yancey', 'Westrey', 'Recruiter');
insert into person (first_name, last_name, profession) values ('Ignacio', 'Dunbar', 'VP Accounting');
insert into person (first_name, last_name, profession) values ('Ernest', 'Washbrook', 'Civil Engineer');
insert into person (first_name, last_name, profession) values ('Carlene', 'Lief', 'Software Consultant');
insert into person (first_name, last_name, profession) values ('Manfred', 'Kopelman', 'Paralegal');
insert into person (first_name, last_name, profession) values ('Marillin', 'Dyott', 'Analog Circuit Design manager');
insert into person (first_name, last_name, profession) values ('Tristan', 'Merrin', 'Computer Systems Analyst II');
insert into person (first_name, last_name, profession) values ('Jessalin', 'Aleksahkin', 'Clinical Specialist');
insert into person (first_name, last_name, profession) values ('Blane', 'Raggatt', 'Environmental Tech');
insert into person (first_name, last_name, profession) values ('Skylar', 'Thorneley', 'Automation Specialist I');
insert into person (first_name, last_name, profession) values ('Bondon', 'Aubri', 'Quality Engineer');
insert into person (first_name, last_name, profession) values ('Alecia', 'Nevitt', 'Sales Associate');